added ability to disable efi hash-check added choise partition / efi file

diff --git a/usr/lib/initcpio/install/sd-chkcryptoboot b/usr/lib/initcpio/install/sd-chkcryptoboot
--- a/usr/lib/initcpio/install/sd-chkcryptoboot
+++ b/usr/lib/initcpio/install/sd-chkcryptoboot
@@ -5,21 +5,37 @@ build() {
 
 	add_dir "/etc/sd-chkcryptoboot"
 
-	if [ $BOOTDISK ]; then
+	if [ $SECTORS ]; then
 		touch /tmp/head.b2sum;
-		dd if=$BOOTDISK bs=512 count=$SECTORS | b2sum > /tmp/head.b2sum;
+		dd if=/dev/disk/by-id/$BOOTDISKID bs=512 count=$SECTORS | b2sum > /tmp/head.b2sum;
 		chown root:root /tmp/head.b2sum;
 		chmod 600 /tmp/head.b2sum;
 		add_file "/tmp/head.b2sum" "/etc/sd-chkcryptoboot/head.b2sum";
 	fi
 
-	if [ $ESP ]; then
-		touch /tmp/esp.b2sum;
-		dd if=$ESP bs=4M | b2sum > /tmp/esp.b2sum;
-		chown root:root /tmp/esp.b2sum;
-		chmod 600 /tmp/esp.b2sum;
-		add_file "/tmp/esp.b2sum" "/etc/sd-chkcryptoboot/esp.b2sum";
+
+	if [ $ESPPART ]; then
+		touch /tmp/efi.b2sum;
+		EFIMOUNT=$(mount | grep $(readlink -f /dev/disk/by-id/$BOOTDISKID-part$ESPPART) | awk '{print 3}')
+
+		if [ ! $EFIMOUNT ]; then
+			echo "ERROR: Your ESP is not mounted! Mount ESP and regenerate initrd.";
+			exit 1;
+		fi
+
+		if [ $EFIPATH ]; then
+			dd if=$($EFIMOUNT/$EFIPATH) | b2sum > /tmp/efi.b2sum;
+			chown root:root /tmp/efi.b2sum;
+			chmod 600 /tmp/efi.b2sum;
+			add_file "/tmp/efi.b2sum" "/etc/sd-chkcryptoboot/efi.b2sum";
+		else
+			dd if=$(/dev/disk/by-id/$BOOTDISKID-part$ESPPART) | b2sum > /tmp/efi.b2sum
+			chown root:root /tmp/efi.b2sum;
+			chmod 600 /tmp/efi.b2sum;
+			add_file "/tmp/efi.b2sum" "/etc/sd-chkcryptoboot/efi.b2sum";
+		fi
 	fi
+
 
 	touch /tmp/{lspci,lsusb,lsblk}.b2sum
 	chown root:root /tmp/{lspci,lsusb,lsblk}.b2sum
